# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fudge_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=fudge_api.models.upload_to)),
            ],
            options={
                'ordering': ('created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('total_income', models.FloatField(default=0.0)),
                ('total_expenses', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=fudge_api.models.upload_to)),
            ],
            options={
                'ordering': ('created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=fudge_api.models.upload_to)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='fudge_api.Category')),
            ],
            options={
                'ordering': ('created_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fudge_api.Budget')),
            ],
            options={
                'ordering': ('created_date',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subcategory',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='fudge_api.Transaction'),
        ),
        migrations.AddField(
            model_name='category',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='fudge_api.Transaction'),
        ),
        migrations.AddField(
            model_name='account',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='fudge_api.Budget'),
        ),
    ]
