# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudge_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='fudge_api.Budget'),
        ),
        migrations.AlterField(
            model_name='category',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='fudge_api.Transaction'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='fudge_api.Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='fudge_api.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fudge_api.Budget'),
        ),
    ]
