# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudge_api', '0002_auto_20170506_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='fudge_api.Category'),
        ),
    ]
