# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudge_api', '0004_auto_20170506_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fudge_api.Category'),
        ),
    ]
